# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb765462a3ffe742d439b8fc9df917ff"
name = "Nutan-Ex-1"
handle = "nutan-ex-1"
application_url = "https://example.com/"
embedded = true

[webhooks]
api_version = "2024-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
