# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ee99d92f45a514a6836fb6c2c3dab0fa"
name = "Chectou Shop Agentic AI"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,write_draft_orders,read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true
